// The Sharp Edge — recipe data. q: number | [lo,hi] | null (to taste / unscaled). u: unit ('' = count). ['H','Name'] = section header.
export const CATS = ["Sauces, Dressings & Salsas","Marinades & Rubs","Salads","Soups & Stews","Tacos & Sandwiches","Pasta & Noodles","Entrées","Side Dishes","Breakfast","Drinks"];

export const RECIPES = [
{id:"mango-salsa",cat:"Sauces, Dressings & Salsas",title:"Mango Salsa",gf:true,base:2,unit:"cups",meta:"About 2 cups · salmon, grilled seafood, chicken, tacos, rice bowls, chips",
ing:[[1,"","ripe mango, peeled and diced"],[0.25,"","red onion, finely diced"],[0.5,"","red bell pepper, finely diced"],[1,"","small jalapeño, seeded and minced (optional)"],[2,"tbsp","fresh cilantro, chopped"],[1,"tbsp","fresh mint, chopped (optional)"],[1,"","lime, juiced"],[1,"tsp","honey or maple syrup (optional)"],[0.25,"tsp","kosher salt"],[null,"","freshly ground black pepper, to taste"]],
steps:["Combine the mango, red onion, bell pepper, jalapeño, cilantro and mint in a bowl.","Add the lime juice, honey, salt and black pepper.","Toss gently so the mango keeps its shape.","Let the salsa rest 10–15 minutes before serving.","Taste and adjust with more lime or salt."],
notes:["Make no more than a few hours ahead for the best texture.","Diced cucumber for crunch; half an avocado (added just before serving) for richness."]},

{id:"cucumber-dressing",cat:"Sauces, Dressings & Salsas",title:"Thai-Japanese Cucumber Dressing",gf:"check",gfNote:"Use GF tamari; wasabi oil formulations vary — check the label.",base:2,unit:"cucumbers",meta:"Enough for 2 large cucumbers · also cold noodles, slaw, grilled salmon",
ing:[[2,"tbsp","tamari or soy sauce"],[1.5,"tbsp","rice vinegar"],[2,"tsp","sesame oil"],[1,"tsp","wasabi oil"],[1,"tsp","honey or maple syrup"],[1,"tsp","freshly grated ginger"],[1,"","small garlic clove, finely grated"],[1,"tsp","lime juice"],[0.5,"tsp","chili crisp (optional)"],[1,"tsp","toasted sesame seeds"]],
steps:["Whisk the tamari, rice vinegar, sesame oil, wasabi oil, honey, ginger, garlic and lime juice together.","Taste before adding chili crisp — it should be salty, bright, lightly sweet and aromatic, not aggressively hot.","Add the sesame seeds just before tossing with the cucumbers."],
notes:["Wasabi oil varies widely in strength — start with ½ tsp if the bottle is pungent."]},

{id:"raspberry-vinaigrette",cat:"Sauces, Dressings & Salsas",title:"Raspberry Vinaigrette",gf:true,base:1,unit:"batches",meta:"One batch (~½ cup) · chilled chicken, goat cheese and raspberry salad",
ing:[[2,"tbsp","raspberry jam (or ⅓ cup fresh raspberries, mashed and strained)"],[0.25,"cup","olive oil"],[2,"tbsp","white wine or balsamic vinegar"],[1,"tsp","Dijon mustard"],[1,"tsp","honey"],[null,"","salt and pepper, to taste"]],
steps:["Whisk everything together until emulsified, or shake in a jar.","Taste — it should echo the berries without overpowering the goat cheese. Adjust honey or vinegar."],
notes:["Salad pairing: chilled chicken, goat cheese, fresh raspberries, candied pecans, thin red onion, baby spinach or arugula.","Lighter alternatives for the same salad: honey-balsamic, poppy seed, or lemon-honey vinaigrette."]},

{id:"bourbon-butter",cat:"Sauces, Dressings & Salsas",title:"Bourbon-Shallot Seafood Butter",gf:"check",gfNote:"Naturally GF — confirm the Worcestershire label.",base:12,unit:"coins",meta:"One ~250 g log · chargrilled oysters, lobster — built to pair with a pour of bourbon",
ing:[[250,"g","unsalted butter, softened"],[3,"tbsp","bourbon"],[1,"","shallot, minced fine"],[2,"","garlic cloves, minced"],[1,"tsp","maple syrup"],[1,"","lemon — zest, plus 1 tsp juice"],[1,"tsp","gluten-free Worcestershire"],[0.5,"tsp","smoked paprika"],[0.25,"tsp","cayenne"],[2,"tbsp","chives, minced"],[1,"tbsp","flat-leaf parsley, minced"],[0.75,"tsp","kosher salt"],[0.25,"tsp","black pepper"]],
steps:["Sweat shallot and garlic in 1 tbsp of the butter over medium, 2–3 min, no browning. Add bourbon and maple; reduce to a syrupy tablespoon.","Cool the reduction completely — warm splits the log.","Beat the remaining butter until creamy; add the reduction and everything else. Taste salt against how briny your oysters run.","Roll into a 4 cm log in parchment; chill 2+ hours."],
notes:["Oysters: a coin per shucked shell, screaming grill 4–5 min until the liquor bubbles. Optional parm the last minute.","Lobster: coins under the split shell before grilling, or melt as the dipping butter.","Raw oysters get nothing — brush melted butter on grilled bread alongside instead.","Fridge 1 week, freezer 3 months; slice coins straight from frozen.","Flatters wheated bourbons (Maker's, Buffalo Trace); ease the cayenne for high-rye pours."]},

{id:"flank-marinade-quick",cat:"Marinades & Rubs",title:"Flank Steak Marinade — Quick (4–8 hr)",gf:"check",gfNote:"GF with tamari and a GF-labelled Worcestershire (Lea & Perrins Canada is GF).",base:15,unit:"servings",meta:"Coats ~5–6 lb flank (4–6 steaks)",
ing:[[[5,6],"lb","flank steak (4–6 steaks)"],[1,"cup","soy sauce (or tamari for gluten-free)"],[0.75,"cup","olive oil"],[0.75,"cup","brown sugar, packed"],[6,"tbsp","red wine vinegar"],[3,"tbsp","Worcestershire sauce"],[12,"","garlic cloves, minced"],[1.5,"tsp","black pepper"],[1,"tbsp","fresh ginger, grated (optional)"],[6,"","green onions, sliced (optional)"]],
steps:["Whisk until the sugar dissolves.","Split steak and marinade across 2 zip bags.","Refrigerate 4–8 hours. Do not exceed ~12 hours at this salt/acid level.","Grill hot and fast; rest, then slice thin against the grain."],
notes:["No Dijon mustard (confirmed preference)."]},

{id:"flank-marinade-overnight",cat:"Marinades & Rubs",title:"Flank Steak Marinade — Overnight (12–18 hr)",gf:"check",gfNote:"GF with tamari and a GF-labelled Worcestershire.",base:15,unit:"servings",meta:"Coats ~5–6 lb flank (4–6 steaks)",prov:"v2 of the quick marinade — less soy and vinegar so the surface doesn't over-cure, more oil to protect.",
ing:[[[5,6],"lb","flank steak (4–6 steaks)"],[0.5,"cup","soy sauce (or tamari for gluten-free)"],[0.75,"cup","olive oil"],[0.5,"cup","brown sugar, packed"],[3,"tbsp","red wine vinegar"],[2,"tbsp","Worcestershire sauce"],[10,"","garlic cloves, minced"],[1.5,"tsp","black pepper"],[1,"tbsp","fresh ginger, grated"],[6,"","green onions, sliced"]],
steps:["Whisk until the sugar dissolves.","Divide steak and marinade between 2 large zip bags, press out air, turn to coat. Refrigerate overnight — 12–18 hours is fine at these proportions.","Pull steaks out 30–45 minutes before cooking. Pat dry so they sear instead of steam.","Grill over high direct heat, 4–5 minutes per side for medium-rare (54–57 °C internal), in batches so the grill stays hot.","Rest 8–10 minutes, then slice thin against the grain at an angle."]},

{id:"souvlaki-marinade",cat:"Marinades & Rubs",title:"Chicken Souvlaki Marinade",gf:true,base:15,unit:"servings",meta:"For 5 lb boneless skinless chicken thighs",
ing:[[5,"lb","boneless skinless chicken thighs"],[0.5,"cup","olive oil"],[4,"","lemons, juiced"],[6,"","garlic cloves, minced"],[3,"tbsp","dried oregano"],[2,"tsp","salt"],[1,"tsp","pepper"]],
steps:["Whisk marinade and coat chicken.","Refrigerate overnight (minimum 2 hours).","Thread onto skewers or grill whole."]},

{id:"cucumber-salad",cat:"Salads",title:"Thai-Japanese Cucumber Salad",gf:"check",gfNote:"Use GF tamari; check the wasabi oil label.",base:4,unit:"servings",meta:"Side for 4 · 15 min plus optional draining",
ing:[[2,"","large English cucumbers"],[0.5,"tsp","kosher salt"],[2,"tbsp","tamari or soy sauce"],[1.5,"tbsp","rice vinegar"],[2,"tsp","sesame oil"],[1,"tsp","wasabi oil"],[1,"tsp","honey or maple syrup"],[1,"tsp","freshly grated ginger"],[1,"","small garlic clove, finely grated"],[1,"tsp","lime juice"],[2,"tbsp","fresh cilantro, roughly chopped"],[2,"tbsp","fresh mint, roughly chopped"],[2,"","green onions, thinly sliced"],[1,"tsp","toasted sesame seeds"],[0.5,"tsp","chili crisp (optional)"]],
steps:["Slice the cucumbers thinly. For more texture, lightly smash them first and cut into irregular bite-sized pieces.","Toss the cucumbers with the salt and drain in a colander 15–20 minutes.","Pat the cucumbers dry with a clean towel.","Whisk together the tamari, rice vinegar, sesame oil, wasabi oil, honey, ginger, garlic and lime juice.","Add the cucumbers, cilantro, mint and green onions.","Toss thoroughly and finish with sesame seeds and chili crisp.","Serve immediately or chill up to 30 minutes."],
notes:["Optional additions: crushed peanuts or cashews, thin radish, shredded carrot, edamame, crispy shallots, diced avocado."]},

{id:"watermelon-feta",cat:"Salads",title:"Watermelon-Feta-Mint Salad",gf:true,base:15,unit:"servings",meta:"Side for ~15 · scale down freely",
ing:[[1,"","large watermelon (10–12 lb), cubed"],[[1.5,2],"lb","block feta in brine, cubed or crumbled"],[1,"","large bunch fresh mint, leaves torn"],[[2,3],"","limes, juiced"],[null,"","olive oil, a light drizzle"],[null,"","flaky salt and black pepper"]],
steps:["Cube the watermelon and chill.","Just before serving, combine watermelon, feta and mint.","Dress with lime juice, a light drizzle of olive oil, salt and pepper. Toss gently."],
notes:["Assemble day-of only — cut watermelon weeps if it sits.","Block feta tastes better than pre-crumbled."]},

{id:"gurkensalat",cat:"Salads",title:"German Creamy Cucumber-Dill Salad (Gurkensalat)",gf:true,base:6,unit:"servings",meta:"Side for 6 · grilled meats, BBQ spreads",
ing:[[2,"","large English cucumbers"],[1,"tsp","kosher salt (for draining)"],[0.5,"cup","sour cream, full fat"],[0.25,"cup","Greek yogurt, plain full fat"],[1,"","small garlic clove, finely grated"],[3,"tbsp","fresh dill, chopped"],[1,"tbsp","white wine vinegar or lemon juice (optional, for lift)"],[0.5,"tsp","sugar (optional, traditional)"],[0.25,"tsp","black pepper, plus salt to taste"]],
steps:["Shave the cucumbers into thin 2–3 mm rounds.","Toss with the salt; drain in a colander 20–30 min, then squeeze gently in handfuls and discard the liquid.","Stir the dressing together; season lightly — the cucumbers bring salt from draining.","Fold in the cucumbers; chill 30–60 min. Serve within a few hours, extra dill on top."],
notes:["2:1 sour cream to yogurt keeps it light without losing richness; all sour cream for old-school.","Dairy in summer — keep it shaded or nested in ice outdoors."]},

{id:"broccoli-slaw",cat:"Salads",title:"Pineapple Mango Broccoli Slaw",gf:"check",gfNote:"GF if the dressing is homemade — skip bottled dressings; tamari for any savoury splash.",base:15,unit:"servings",meta:"Side for ~15",prov:"Household version — broccoli slaw bag base, creamy cider-vinegar dressing, no Dijon. Dressing quantities pending transcription from the paper original.",
ing:[[[1,2],"bag","broccoli slaw mix"],[3,"","ripe mangos, diced"],[4,"cup","fresh pineapple, diced"],[null,"","fresh cilantro, chopped"],[null,"","creamy dressing: mayonnaise (± Greek yogurt), apple cider vinegar, honey or maple syrup, salt, pepper"]],
steps:["Whisk the dressing.","Combine slaw base with fruit and cilantro.","Dress a few hours before serving — the slaw improves as it sits, but hold salt and dressing until a few hours out so it doesn't weep."]},

{id:"goulash",cat:"Soups & Stews",title:"Gluten-Free Hungarian Beef Goulash",gf:true,base:6,unit:"servings",meta:"Rich, paprika-forward beef stew thickened naturally with potatoes — no flour, no roux",
ing:[[2,"lb","beef chuck, cut into 1-inch cubes"],[3,"tbsp","vegetable oil or lard"],[3,"","yellow onions, diced"],[4,"","garlic cloves, minced"],[3,"tbsp","sweet Hungarian paprika (certified GF)"],[1,"tsp","smoked or hot paprika"],[1,"tsp","caraway seeds, crushed"],[2,"tbsp","tomato paste"],[2,"","red bell peppers, diced"],[3,"cup","beef broth (certified GF)"],[2,"","bay leaves"],[1.5,"lb","Yukon Gold potatoes, cubed"],[1.5,"tsp","salt"],[0.5,"tsp","black pepper"]],
steps:["Sear the beef: pat dry, season with salt and pepper. Heat the oil in a heavy Dutch oven over medium-high and brown in batches, ~8 minutes total. Set aside.","Soften the onions: lower heat to medium, cook until deeply softened and golden, ~10 minutes. Add garlic; 1 minute more.","Bloom the spices: pull the pot off the heat so the paprika doesn't scorch. Stir in both paprikas, caraway and tomato paste ~30 seconds until fragrant.","Build the stew: return the beef and juices. Add peppers, broth and bay leaves. Simmer covered, low and slow, until fork-tender, ~90 minutes.","Add potatoes: simmer uncovered until tender and the broth thickens from their starch, ~30 minutes.","Finish: discard bay leaves, adjust seasoning, rest 10 minutes."],
notes:["Three hidden-gluten checkpoints: paprika (wheat anti-caking in cheap blends), beef broth/bouillon, tomato paste.","To thicken further without flour: mash a few potato cubes against the pot and stir back in — the traditional Hungarian way.","Serve with sour cream, GF egg noodles or rice. Better the next day; freezes 3 months."]},

{id:"tequila-lime-chicken",cat:"Tacos & Sandwiches",title:"Tequila Lime Chicken — Tacos or Club",gf:"check",gfNote:"Taco build on 100% corn tortillas is GF; the club build is not.",base:4,unit:"servings",meta:"Serves 4 · marinate 4 hr to overnight",prov:"food.com #493784 — house use is the taco filling; the club is the original format.",
ing:[["H","Tequila lime marinade"],[4,"","boneless skinless chicken breasts (~4 oz each), lightly flattened"],[0.25,"cup","tequila"],[0.5,"cup","lime juice"],[2,"tbsp","olive oil"],[1,"tsp","lime zest"],[1,"","jalapeño"],[2,"","garlic cloves"],[0.25,"cup","cilantro, leaves and tender stems"],[1,"tsp","ancho or chipotle chile powder"],[1,"tsp","ground cumin"],[null,"","salt and black pepper (on the chicken at the grill)"]],
steps:["Blitz everything except the chicken, salt and pepper in a food processor until smooth.","Bag with the chicken, massage to coat. Marinate at least 4 hours or overnight.","Grill medium-high on oiled grates; season with salt and pepper. ~5–7 min per side until cooked through.","Taco build: slice or chop. Warm corn tortillas, guacamole or avocado, mango salsa (on file — perfect match), crumbled queso fresco, cilantro, lime wedge. Chipotle mayo optional.","Club build: toasted bun, jalapeño or chipotle mayo (½ cup mayo + 1 tbsp adobo), lettuce, tomato, 2 slices crisp smoky bacon, generous guacamole, queso fresco."],
notes:["The marinade also works over burrito bowls and salads.","Half a cup of lime juice is a lot of acid — don't push much past overnight or the surface goes mealy."]},

{id:"spaghetti-sauce-2009",cat:"Pasta & Noodles",title:"Family Spaghetti Sauce (2009)",gf:"check",gfNote:"Canned sauces vary — check labels; serve over GF pasta if needed.",base:8,unit:"servings",meta:"Big batch — freezes well",prov:"Family recipe, 2009. Herb quantities and method to be confirmed against the paper original.",
ing:[[2,"lb","ground beef, extra lean"],[[3,4],"","celery sticks, diced"],[2,"","peppers, red + green"],[null,"","garlic"],[null,"","tomato paste"],[1,"can","diced tomatoes"],[1,"can","tomato juice"],[2,"can","spaghetti sauce"],[null,"","herbs, including marjoram"]],
steps:["Brown the beef in a large pot; drain if needed.","Add diced celery and peppers; soften 5–8 minutes. Garlic for the last minute.","Stir in tomato paste; cook 1–2 minutes to darken.","Add diced tomatoes, tomato juice, and both cans of sauce.","Season with marjoram, oregano, basil, bay, salt, pepper.","Simmer low and partially covered 1–2+ hours, stirring occasionally."]},

{id:"salmon-mango-salsa",cat:"Entrées",title:"Salmon with Mango Salsa",gf:true,base:4,unit:"fillets",meta:"Serves 4 · 15 min prep, 10–14 min cook",
ing:[["H","Salmon"],[4,"","salmon fillets, 170–200 g each"],[1,"tbsp","avocado oil or olive oil"],[1,"tsp","kosher salt"],[1,"tsp","smoked paprika"],[0.5,"tsp","ground cumin"],[0.5,"tsp","garlic powder"],[0.25,"tsp","freshly ground black pepper"],[1,"","lime, zested"],["H","Mango salsa"],[1,"","ripe mango, diced"],[0.25,"","red onion, finely diced"],[0.5,"","red bell pepper, diced"],[1,"","small jalapeño, seeded and minced (optional)"],[2,"tbsp","chopped cilantro"],[1,"","lime, juiced"],[0.25,"tsp","kosher salt"]],
steps:["Heat the oven to 220 °C / 425 °F.","Pat the salmon dry; place skin-side down on a lined baking sheet.","Rub the salmon with oil.","Combine salt, smoked paprika, cumin, garlic powder, pepper and lime zest. Season evenly.","Bake 10–14 minutes, depending on thickness, until the centre flakes but stays moist.","While it cooks, combine the salsa ingredients.","Rest the salmon 2 minutes.","Spoon the salsa generously over each fillet and serve."],
notes:["Grill method: medium-high, oiled grates. Skin-side down 5–7 min, flip carefully, 2–4 min more. Salsa goes on off the grill.","Sides: coconut rice, cilantro-lime rice, grilled asparagus, roasted sweet potatoes, Thai-Japanese cucumber salad, simple slaw."]},

{id:"flank-stir-fry",cat:"Entrées",title:"Flank Steak Stir-Fry with Black Bean–Hoisin Sauce",gf:"check",gfNote:"GF with tamari — but hoisin and black bean sauce often contain wheat; check labels.",base:4,unit:"servings",meta:"Serves 3–4 · baseline 1 lb steak; tested to 800 g — sear in batches at that volume",prov:"Originally built around leftover fire-roasted vegetables — any cooked or quick-cooking veg works.",
ing:[["H","Velveting marinade"],[1,"lb","flank steak, sliced thin against the grain"],[1,"tbsp","tamari"],[1,"tbsp","cornstarch"],[1,"tsp","neutral oil"],[0.5,"tsp","baking soda (optional — tenderizes)"],["H","Sauce"],[1,"tbsp","black bean sauce"],[1.5,"tbsp","hoisin"],[3,"tbsp","water"],[2,"","garlic cloves, minced"],[1,"tsp","fresh ginger, minced"],["H","Everything else"],[0.33,"cup","cashews"],[[2,3],"cup","cooked or leftover vegetables"],[null,"","jasmine rice (microwave rice works great)"],[null,"","finishing: white sesame oil off heat; chili crisp at the table"]],
steps:["Marinate: toss the sliced steak with tamari, cornstarch, oil and baking soda. Rest 20–30 minutes at room temp.","While it sits: mix the sauce; start the rice when the steak has ~10 minutes left.","Toast cashews in a dry pan, 2–3 minutes. Remove.","Sear the steak in a hot oiled pan, 1–2 minutes. Remove. Batches if scaled up.","Revive the veggies in the same hot pan, 1–2 minutes — they're already cooked, just warm them.","Combine: steak, veggies, cashews and sauce back in the pan; toss 1 minute to glaze.","Plate over rice. Drizzle sesame oil off the heat; chili crisp on the side."],
notes:["Wine: Zinfandel first choice; Grenache lighter; avoid Cabernet Sauvignon — tannin clashes with soy sauces.","Premium sesame oil (e.g. Henko) is a finishing oil only — never cook with it."]},

{id:"celeriac-puree",cat:"Side Dishes",title:"Celeriac Purée with Infused Milk & Cream",gf:true,base:4,unit:"servings",meta:"Serves 4 · the milk and cream steep with garlic, thyme and bay before the celeriac goes in",
ing:[[900,"g","celeriac (celery root), peeled, 2 cm cubes"],[500,"ml","whole milk"],[120,"ml","heavy cream"],[3,"","garlic cloves, lightly crushed"],[3,"","thyme sprigs"],[1,"","bay leaf"],[0.5,"tsp","black peppercorns"],[50,"g","cold unsalted butter"],[1,"tsp","salt"],[null,"","pinch of freshly grated nutmeg"]],
steps:["Infuse: combine milk, cream, garlic, thyme, bay and peppercorns. Warm to a bare simmer, off heat, steep ~15 minutes. Never a hard boil.","Simmer: add the celeriac to the infused liquid, aromatics still in. Gentle simmer until completely fork-tender, ~20 minutes. Keep low so the milk doesn't catch.","Strain: lift the celeriac into a blender. Strain and reserve the cooking liquid; discard aromatics.","Blend with the cold butter, adding reserved liquid a splash at a time until glossy and silky. Less liquid = pipeable; more = spoonable. Sieve for true velvet.","Season: salt, nutmeg, taste, serve warm."],
notes:["Cooking the celeriac in the infused milk rather than water is the whole trick — it seasons from the inside.","Pairs beautifully with steak; rich, so keep the rest of the plate light."]},

{id:"pancakes",cat:"Breakfast",title:"Classic Fluffy Pancakes",gf:false,base:10,unit:"pancakes",meta:"About 10 medium pancakes · serves 3–4",
ing:[[1.5,"cup","all-purpose flour"],[3.5,"tsp","baking powder"],[1,"tbsp","granulated sugar"],[0.5,"tsp","kosher salt"],[1.25,"cup","milk"],[1,"","large egg"],[3,"tbsp","melted butter, plus more for the pan"],[1,"tsp","vanilla extract"]],
steps:["Whisk the flour, baking powder, sugar and salt in a large bowl.","In a second bowl, whisk the milk, egg, melted butter and vanilla.","Pour the wet into the dry.","Stir only until no large dry patches remain — small lumps are desirable.","Rest the batter 5–10 minutes.","Heat a lightly buttered skillet or griddle over medium.","Pour about ¼ cup of batter per pancake.","Cook until bubbles appear and the edges look dry, ~2 minutes.","Flip; another 1–2 minutes.","Serve immediately."],
notes:["Drop-ins (after pouring onto the griddle): blueberries, banana, chocolate chips, pecans, cinnamon, lemon zest.","Serving: maple syrup + salted butter, berries + whipped cream, peanut butter + banana, warm apple compote — or mango salsa for sweet-savoury."]},

{id:"visinata",cat:"Drinks",title:"Vișinată (Romanian Sour Cherry Liqueur)",gf:true,base:1,unit:"jars (4 L)",meta:"Per 4 L jar batch · 6–8 weeks minimum",prov:"In progress — final quantities pending batch size decision.",
ing:[[2,"kg","sour cherries (vișine), stems removed, unpitted"],[[0.7,1],"kg","sugar, to taste"],[[1.5,2],"L","spirit"]],
steps:["Layer cherries and sugar in a large jar; macerate in a sunny spot until the sugar draws out the juice — a few days to 2 weeks.","Add the spirit, seal, rest in a cool dark place 6–8 weeks minimum, shaking occasionally.","Strain, bottle, and age further — it improves markedly at 3+ months."],
notes:["Starting proof matters: 76% spirit lands near the traditional 28–32% finished strength; standard 40% vodka gives a lighter ~18–22% — still good, just softer.","Two 750 ml bottles of high-proof spirit ≈ one 4 L batch."]}
];

export const GLUTEN_GUIDE = [
{h:"At the grill",items:["Shared grates: scrub hot or use foil if breaded or gluten-marinated food was cooked on them.","Bottled sauces: coleslaw dressing, Worcestershire (barley malt in many), regular soy sauce, many BBQ sauces. Anything you mix yourself from oil, citrus and herbs is safe by default.","Serving utensils: keep separate so gluten-eating guests don't double-dip GF dishes."]},
{h:"Pantry traps",items:["Soy sauce → gluten-free tamari whenever gluten avoidance matters.","Wasabi oil is often GF but formulations vary — check for wheat, barley, malt, regular soy sauce, or a \"may contain wheat\" line.","Worcestershire: many use barley malt — Lea & Perrins Canada is GF; check your bottle."]},
{h:"Goulash checkpoints",items:["Paprika — cheap blends may use wheat anti-caking filler.","Beef broth and bouillon.","Tomato paste."]}
];
